terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.12.0"
    }
  }
}

# The config file was generated by Layer 1! Modular beb.
provider "helm" {
  kubernetes {
    config_path = "${path.module}/../layer1-cluster/kubeconfig.yaml"
  }
}
